### ISSUE TITLE
How to understand the Probabilities

### ISSUE THREAD

**Issue by endeffects** [accord-net/framework#747]
Hallo,

i have trained my SVM with a OneVsMany + Polynomial + SecondOrder + 55 Vectors Setup.
Now i'd like to calculate the Probabilities for some new Input Data.

I did not found much about it in the documentation, so my first question is,
do i have to use the "raw" input data or the zscores for it?

And my second question is, how do i have to understand the result 
of the Probabilities for the following Example?

I don't understand why the numbers are getting so high 
and what each number mean. I have expected a maximum 
of 1.0 (= 100%) in total (sum of all values).

```
var inputData = this.trainingSet.Data.ToJagged<double>( vectors );
var inputDataScore = Accord.Statistics.Tools.ZScores( inputData );
```

**Raw Input**

machine.Probabilities( inputData[ 1000 ] );
{double[3]}
    [0]: 2.1525574762352978E+46
    [1]: 2.0443865729138803E+28
    [2]: 5.5206145567606157E-46

machine.Probabilities( inputData[ 2000 ] );
{double[3]}
    [0]: 5.5592506085602989E+199
    [1]: 6.1912561927174E+46
    [2]: 0

machine.Probabilities( inputData[ 3000 ] );
{double[3]}
    [0]: 5.02989199542716E+229
    [1]: 6.7457303591241874E-17
    [2]: 1.1459520773663916E+40

machine.Probabilities( inputData[ 7000 ] );
{double[3]}
    [0]: 6.7922716748069132E+77
    **[1]: 367458100.94832218**
    [2]: 6.7917792409261419E-80

**ZScores**

machine.Probabilities( inputDataScore[ 1000 ] );
{double[3]}
    [0]: 0.000742370879781349
    [1]: 0.033503026346568827
    **[2]: 366.37933312215193**

machine.Probabilities( inputDataScore[ 2000 ] );
{double[3]}
    [0]: 154.37274078540852
    [1]: 0.04022262865457045
    [2]: 0.00017140345326030072

machine.Probabilities( inputDataScore[ 3000 ] );
{double[3]}
    [0]: 0.0003500804157922651
    [1]: 0.035703246397950021
    **[2]: 2637.2725526589952**

machine.Probabilities( inputDataScore[ 9000 ] );
{double[3]}
    [0]: 0.00056572280086877229
    **[1]: 6536.0396566783138**
    [2]: 2.2543104041819597E-05

**Comment by cesarsouza** [comment]
Hi @endeffects, 

Can you please post an example of your data so I can take a look? Indeed the probabilities were supposed to be summing up to 1.0.

Since you mentioned you are using the SecondOrder method, are you calibrating the machine using the [ProbabilisticOutputCalibration class](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_ProbabilisticOutputCalibration.htm) after you have trained it using SMO?
 
Regards,
Cesar

**Comment by endeffects** [comment]
Yes, i'm using the calibration like below. I also have uploaded my input test data:
https://1drv.ms/u/s!AvfU-VGBgXuLg7UTt20vi48puPZzBw

```
        var teacher = TrainingMachineFactory.CreateTeacher();
        var machine = teacher.Learn( this.trainingInputData, this.trainingOutputData );

        var calibrator = TrainingMachineFactory.CreateCalibrator( machine );
        machine = calibrator.Learn( this.trainingInputData, this.trainingOutputData );

        internal static MultilabelSupportVectorLearning<Polynomial> CreateTeacher()
        {                        
            var kernel = new Polynomial(2, 0.25);
                                                          
            var teacher = new MultilabelSupportVectorLearning<Polynomial>
            {
                Learner =  (param) =>
                    new SequentialMinimalOptimization<Polynomial>
                    {
                        Kernel = kernel,
                        Strategy = SelectionStrategy.SecondOrder,  
                    },
                ParallelOptions = new ParallelOptions { MaxDegreeOfParallelism = 1 }

            };

            return teacher;
        }

        internal static MultilabelSupportVectorLearning<Polynomial> CreateCalibrator(
            MultilabelSupportVectorMachine<Polynomial> machine)
        {
            var calibrator = new MultilabelSupportVectorLearning<Polynomial>
            {
                Model = machine,

                Learner = (param) => new ProbabilisticOutputCalibration<Polynomial> {Model = param.Model}
            };

            return calibrator;
        }
```

**Comment by cesarsouza** [comment]
Hi @endeffects,

Thanks a lot for providing the data and source code. I've been able to identify the issue, but it might take a little bit of time until the fix is available as a pre-release.

In the mean time, you can fix that issue by applying a little modification to the output of the scores method. Please consider the following method:

```csharp
public static double[] CorrectProbabilities(IMultilabelLikelihoodClassifier<double[]> machine, double[] input)
{
    return Special.Softmax(machine.Scores(input).Apply(x => -Special.Log1pexp(-x)));
}
```

With this method, you should be able to obtain the correct probabilities using

```csharp
double[] probabilities = CorrectProbabilities(machine, inputs[0]);
```

Regards and thanks again for reporting the issue,

Cesar

**Comment by endeffects** [comment]
Thanks alot for your unremitting support and the fast help. I tried your fix, but i'm getting still values greater than 1.0. Please try the following examples, 2 of them are greater than 1.

```
            var probabilities = CorrectProbabilities( machine, inputData[ 0 ] );
            probabilities = CorrectProbabilities( machine, inputData[ 1000 ] );
            probabilities = CorrectProbabilities( machine, inputData[ 10000 ] );
            probabilities = CorrectProbabilities( machine, inputData[ 20000 ] );
```

**Comment by cesarsouza** [comment]
Hi @endeffects,

Thanks for the update. Actually, I have been experimenting with a subset of your data, because my laptop is not powerful enough to train SVMs with all your data points in a suitable amount of time. However, I have to say that using my current setup (subsampling 5,000 samples from your original ~20,000 dataset) I have not been able to reproduce the values greater than 1 that you have reported.

I will try to generate a new pre-release version of the framework so you can try it without the need for a workaround. Maybe I have introduced some other fixes that influenced in the behavior of the workaround I had proposed.

I might be able to generate a new pre-release version this weekend.

Regards,
Cesar

**Comment by endeffects** [comment]
I have upgraded to the latest pre-release and also added your changes to my local version, but the problem still exists. :(

**Comment by cesarsouza** [comment]
How far are those values from 1?

**Comment by endeffects** [comment]
I picked some examples from 2 different input sets. 

```
probabilities = CorrectProbabilities( machine, inputData[ 0 ] );
-		probabilities	{double[3]}	double[]
		[0]	0.5	double
		[1]	0.5	double
		[2]	3.3276959651545075E-177	double

probabilities = CorrectProbabilities( machine, inputData[ 1000 ] );
-		probabilities	{double[3]}	double[]
		[0]	0.5	double
		[1]	0.5	double
		[2]	2.7603072783803078E-46	double

probabilities = CorrectProbabilities( machine, inputData[ 10000 ] );
-		probabilities	{double[3]}	double[]
		[0]	0.00056515711252755818	double
		[1]	0.99941231009272513	double
		[2]	2.2532794747388516E-05	double

probabilities = CorrectProbabilities( machine, inputData[ 20000 ] );
-		probabilities	{double[3]}	double[]
		[0]	0.5	double
		[1]	0.5	double
		[2]	1.3794364897656356E-185	double

```

**Comment by cesarsouza** [comment]
Hi @endeffects 

Thanks a lot! Well, indeed this kind of confirmed one of my suspicions: I have to say that those errors are well inside the allowed precision error for the [Special.Softmax](http://accord-framework.net/docs/html/M_Accord_Math_Special_Softmax.htm) method. As you can see, the sums are indeed different from 1.0, but by only extremely tiny amounts (less than 1e-40 in three of your cases), which is way beyond double precision for the 0.0-1.0 range (1e-16, which would be the expected range for probability values). 

I am almost sure those values sum as close to 1 as we can get within double floating-point precision. 

Regards,
Cesar

**Comment by endeffects** [comment]
Oh thanks for the hint, i did not released this. Now it works as needed.
I have modified your fix, see below.

Have nice weekend. :)

```
        public static decimal[] CorrectProbabilities( IMultilabelLikelihoodClassifier<double[]> machine, double[] input )
        {
            var probabilities =  Special.Softmax( machine.Scores( input ).Apply( x => -Special.Log1pexp( -x ) ) );
            return Array.ConvertAll( probabilities, Convert.ToDecimal );
        }
```

**Comment by cesarsouza** [comment]
A new pre-release package (3.6.4-alpha) has just been uploaded to NuGet. It should contain a fix for this issue.

**Comment by endeffects** [comment]
Thanks alot :)
